### PR TITLE
Trying to create support for distributed proof of work.

### PR DESCRIPTION
**Pull request by adrianegraphene**
Hello, 

Is there any chance of getting distributed proof of work support? I'm still refreshing my Java, but went ahead and made some contributions that are along the lines of what is needed. 

If it helps, I have working Python code that uses DPoW that I can share?

### CODE REVIEW

**Comment by koczadly** [comment]
Hey @adrianegraphene, thanks for the contribution.

Are you referring to the DPOW service provided by The Nano Center (https://dpow.nanocenter.org/)? if so, I think it's probably better off in a separate project/module, as the focus of jNano is primarily to offer integrations with the 'official' node, rather than third-party services. That being said, it's certainly something I'd like to add some kind of support for.

If you're interested in taking on the challenge yourself, you're probably best off creating a separate service class, rather than using the RpcQueryNode and standard request/response classes, as they're designed to be used for communication with the node only.

If you have any questions or need any help, feel free to just ask here and I'll do my best to respond (although I might be a bit busy and slow to respond over the next week).

Cheers mate, I appreciate it.

**Comment by adrianegraphene** [comment]
Hello,

Yes, that is what I am referring to. Hmmm, I might be up to that challenge, I'd love to add to your work, it would help my team with our project as well!

Just to be clear, instead of
`src/main/java/uk/oczadly/karl/jnano/rpc/RpcQueryNode.java` 
& request/response folders... 

A separate service class would look like 
`src/main/java/uk/oczadly/karl/jnano/dpow/DpowQueryNode.java`
with its own request/response classes? 

I'd like to be sure that if I put in time to make this, I do it correctly. Thanks!

**Comment by koczadly** [comment]
I'm honestly not too sure what's best, I haven't really had chance to look into their DPoW API system yet.

The general idea is right, but you may just be better off copying the RpcQueryNode and using standard methods to request work, instead of requiring Request and Response classes (assuming their API only offers basic work requests).

So the user of the library would do:
```
// Configure remote service
DpowAPI dpow = DpowAPI("apiKey", other configs....);

// Generate work for the block
String work = dpow.generateWork("635FC6D8D0862A903BE8EEF11A1FA56730A18BA3546A58871AA740BA7287B345");```


I'm honestly not sure though, and I may end up transferring this to a separate third-party service project after rather than including it with jNano.

**Comment by adrianegraphene** [comment]
I think just making an RpcQueryNode clone and tailoring it towards DPoW would be sufficient. I've played around with DPoW quite a bit through Python, but am pretty new at trying to implement it in Java. 

The API does only offer basic work requests. I'll see if we can fork something, test it on our local box, then upload it as a PR. Perfectly fine if you decide to move it to a 3rd party service once we submit PR. Just thought it'd be nice to have something publicly available somewhere so folks don't have to code this from scratch in the future. Hope to update you soon.

**Comment by koczadly** [comment]
I'm sure you probably won't care a year later 😂 but I finally added support for DPoW/BPoW services in version `2.16.0`.

**Pull request closed without merging**
